name: "✨ Feature request"
description: "기능 제안 폼"
title: "[FEAT] 간단 요약을 적어주세요"
labels: ["enhancement", "needs triage"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: 설명
      placeholder: "어떤 기능인지 설명해주세요"
      render: markdown
    validations:
      required: true


